[package]
name = "ckb-plugin-ledger"
version = "0.1.0"
license = "MIT"
authors = [ "Obsidian Systems LLC <maintainer@obsidian.systems>" ]
edition = "2018"
description = "CKB-CLI Plugin for Ledger"
readme = "README.md"
repository = "https://github.com/obsidiansystems/ckb-plugin-ledger/"

[dependencies]
# Same as ckb-cli
ckb-jsonrpc-types = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.34.0-rc1" }
ckb-hash = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.34.0-rc1" }
ckb-crypto = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.34.0-rc1", features = ["secp"] }
ckb-build-info = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.34.0-rc1" }
ckb-types = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.34.0-rc1" }
ckb-util = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.34.0-rc1" }
ckb-resource = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.34.0-rc1" }
ckb-dao-utils = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.34.0-rc1" }

ckb-sdk = { git = "https://github.com/nervosnetwork/ckb-cli", rev = "fcc8b0f54ac447fdf0e0794b600675baa866db32" }
ckb-index = { git = "https://github.com/nervosnetwork/ckb-cli", rev = "fcc8b0f54ac447fdf0e0794b600675baa866db32" }
ckb-cli-plugin-protocol = { git = "https://github.com/nervosnetwork/ckb-cli", rev = "fcc8b0f54ac447fdf0e0794b600675baa866db32" }


serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8.9"

[target.'cfg(unix)'.dependencies]
tui = "0.6.0"
termion = "1.5"